#!/bin/sh
# gen_build_info.sh — js/build_info.js を git メタデータから生成する。
#
# .githooks/pre-commit から呼ばれる。生成物 (js/build_info.js) はそのまま
# コミット・配信される (GitHub Pages / itch はコミット済みファイルを配信するため)。
#
# 記録内容:
#   date  : 生成日 (CalVer, YYYY.MM.DD)。手動更新不要・常に新鮮。
#   hash  : git の短縮ハッシュ (pre-commit 時は親コミット = "based on")。
#   count : コミット総数 (単調増加)。
#   notes : コミットの `Note:` トレーラーを新しい順に収穫したもの (WELCOME 用)。
#
# 素の checkout (フック未実行) でもアプリが動くよう、失敗しても呼び出し側
# (pre-commit) はコミットを止めない。
set -eu

ROOT=$(git rev-parse --show-toplevel)
OUT="$ROOT/js/build_info.js"

DATE=$(date +%Y.%m.%d)
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo 0000000)
COUNT=$(git rev-list --count HEAD 2>/dev/null || echo 0)

# `Note:` トレーラーを収穫 (新しい順・最大 12 件)。JSON 用に \ と " をエスケープ。
NOTES=$(git log -n 400 \
  --pretty=format:'%h%x09%cs%x09%(trailers:key=Note,valueonly=true,separator=%x20)' \
  2>/dev/null \
  | awk -F '\t' 'NF>=3 && $3!="" {
      note=$3;
      gsub(/\\/, "\\\\", note);
      gsub(/"/, "\\\"", note);
      printf "    { date: \"%s\", hash: \"%s\", text: \"%s\" },\n", $2, $1, note;
      c++; if (c >= 12) exit;
    }')

{
  echo "/**"
  echo " * @module build_info"
  echo " * build_info.js — AUTO-GENERATED. Do not edit by hand."
  echo " * Regenerated by tools/gen_build_info.sh via the pre-commit hook."
  echo " * Build stamp (CalVer date + short hash) and user-facing release notes"
  echo " * harvested from commit \`Note:\` trailers (see docs/COMMIT_GUIDE.md)."
  echo " */"
  echo ""
  echo "export const BUILD = {"
  echo "  date: \"$DATE\","
  echo "  hash: \"$HASH\","
  echo "  count: $COUNT,"
  echo "  notes: ["
  printf '%s' "$NOTES"
  echo "  ],"
  echo "};"
} > "$OUT"
